{
 "title": "Avalanche",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "X-Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVAX Benched",
     "type": "graph",
     "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_X_benchlist_benched_weight{package=\"avalanche.public.dappnode.eth\"} / 10^9",
       "legendFormat": "AVAX Benched"
      }
     ]
    },
    {
     "title": "Percentage of Successful Queries",
     "type": "graph",
     "description": "Percentage of queries for which we receive chits on time.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(increase(avalanche_X_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m]) + 1) / (increase(avalanche_X_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m]) + increase(avalanche_X_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m]) + 1)"
      }
     ]
    },
    {
     "title": "Message Handling Time (Total)",
     "type": "graph",
     "description": "Measures how much of each second is being spent handling different kinds of messages on the X-Chain.\\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_X_handler_pull_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_X_handler_push_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_X_handler_chits_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_X_handler_get_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_X_handler_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_X_handler_multi_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_X_handler_get_ancestors_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_X_handler_get_failed_sum{instance=\"avalanche.avalanche.public.dappnode:9650\"}[1m])/1000000000",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_X_handler_query_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_X_handler_get_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_X_handler_get_ancestors_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Message Handling Time (per Message)",
     "type": "graph",
     "description": "Measures how long each kind of request on the X-Chain takes to handle.\\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_X_handler_pull_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_pull_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "pull query"
      },
      {
       "expr": "avalanche_X_handler_push_query_sum{package=\"avalanche.public.dappnode.eth\"}",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_X_handler_chits_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_X_handler_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_X_handler_get_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_get_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_X_handler_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_X_handler_multi_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_multi_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_X_handler_get_ancestors_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_get_ancestors_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_X_handler_get_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_get_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_X_handler_query_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_X_handler_get_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_get_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_X_handler_get_ancestors_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_X_handler_get_ancestors_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Incoming Messages Dropped in Last Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(avalanche_X_handler_dropped[1m])",
       "legendFormat": "Dropped"
      }
     ]
    },
    {
     "title": "Messages Received per Second",
     "type": "graph",
     "description": "Measures how many of each kind of message are received per second on the X-Chain.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_X_handler_pull_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_X_handler_push_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_X_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_X_handler_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_X_handler_get_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_X_handler_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_X_handler_multi_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_X_handler_get_ancestors_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_X_handler_get_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_X_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_X_handler_get_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_X_handler_get_ancestors_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Unprocessed Incoming Messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avalanche_X_handler_pending", "legendFormat": "Pending Messages" }
     ]
    }
   ]
  },
  {
   "title": "P-Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_P_processing{package=\"avalanche.public.dappnode.eth\"}",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Percentage of Successful Queries",
     "type": "graph",
     "description": "Percentage of queries for which we receive chits on time.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(increase(avalanche_P_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[2m]) + 1) / (increase(avalanche_P_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[2m]) + increase(avalanche_P_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[2m]) + 1)"
      }
     ]
    },
    {
     "title": "AVAX Benched",
     "type": "graph",
     "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench\".",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_P_benchlist_benched_weight{package=\"avalanche.public.dappnode.eth\"} / 10^9",
       "legendFormat": "AVAX Benched"
      }
     ]
    },
    {
     "title": "Average Block Rejection Latency",
     "type": "graph",
     "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_P_rejected_sum{package=\"avalanche.public.dappnode.eth\"}[5m]) / rate(avalanche_P_rejected_count{package=\"avalanche.public.dappnode.eth\"}[5m])",
       "legendFormat": "Avg Rejection Latency"
      }
     ]
    },
    {
     "title": "Message Handling Time (Total)",
     "type": "graph",
     "description": "Measures how much of each second is being spent handling different kinds of messages on the P-Chain.\\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_P_handler_pull_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_P_handler_push_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_P_handler_chits_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_P_handler_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_P_handler_get_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_P_handler_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_P_handler_multi_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_P_handler_get_ancestors_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_P_handler_get_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_P_handler_query_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_P_handler_get_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_P_handler_get_ancestors_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Blocks Pending Issuance",
     "type": "graph",
     "description": "The number of blocks that are waiting to be issued because of a missing dependency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_P_blocked{package=\"avalanche.public.dappnode.eth\"}",
       "legendFormat": "Blocks Pending Issuance"
      }
     ]
    },
    {
     "title": "Unprocessed Incoming Messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avalanche_P_handler_pending", "legendFormat": "Pending Messages" }
     ]
    },
    {
     "title": "Accepted Blocks in Last Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(increase(avalanche_P_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m]))",
       "legendFormat": "Accepted"
      }
     ]
    },
    {
     "title": "Rejected Blocks in Last Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(increase(avalanche_P_rejected_count{package=\"avalanche.public.dappnode.eth\"}[1m]))",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "Message Handling Time (per Message)",
     "type": "graph",
     "description": "Measures how long each kind of request on the P-Chain takes to handle.\\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_P_handler_pull_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_pull_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_P_handler_push_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_push_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_P_handler_chits_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_P_handler_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_P_handler_get_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_get_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_P_handler_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_P_handler_multi_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_multi_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_P_handler_get_ancestors_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_get_ancestors_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_P_handler_get_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_get_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_P_handler_query_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_P_handler_get_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_get_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_P_handler_get_ancestors_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_P_handler_get_ancestors_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Incoming Messages Dropped in Last Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(avalanche_P_handler_dropped[1m])"
      }
     ]
    },
    {
     "title": "Average Block Acceptance Latency",
     "type": "graph",
     "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_P_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[5m]) / rate(avalanche_P_accepted_count{package=\"avalanche.public.dappnode.eth\"}[5m])",
       "legendFormat": "Avg Acceptance Latency"
      }
     ]
    },
    {
     "title": "Messages Received per Second",
     "type": "graph",
     "description": "Measures how many of each kind of message are received per second on the P-Chain.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_P_handler_pull_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_P_handler_push_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_P_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_P_handler_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_P_handler_get_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_P_handler_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_P_handler_multi_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_P_handler_get_ancestors_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_P_handler_get_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_P_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_P_handler_get_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_P_handler_get_ancestors_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get ancestors failed"
      }
     ]
    }
   ]
  },
  {
   "title": "C-Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks Pending Issuance",
     "type": "graph",
     "description": "The number of blocks that are waiting to be issued because of a missing dependency.",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_C_blocked{package=\"avalanche.public.dappnode.eth\"}",
       "legendFormat": "Blocks Pending Issuance"
      }
     ]
    },
    {
     "title": "AVAX Benched",
     "type": "graph",
     "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench\".",
     "gridPos": { "h": 7, "w": 6, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_C_benchlist_benched_weight{package=\"avalanche.public.dappnode.eth\"} / 10^9",
       "legendFormat": "AVAX Benched"
      }
     ]
    },
    {
     "title": "Rejected Blocks in Last Minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_C_rejected_count{package=\"avalanche.avalanche.public.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "Incoming Messages Dropped in Last Minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(avalanche_C_handler_dropped[1m])"
      }
     ]
    },
    {
     "title": "Message Handling Time (Total)",
     "type": "graph",
     "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_C_handler_pull_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_C_handler_push_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_C_handler_chits_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_C_handler_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_C_handler_get_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_C_handler_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_C_handler_multi_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_C_handler_get_ancestors_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_C_handler_get_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_C_handler_query_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_C_handler_get_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Accepted Blocks in Last Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(increase(avalanche_C_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m]))"
      }
     ]
    },
    {
     "title": "Processing Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avalanche_C_processing{package=\"avalanche.public.dappnode.eth\"}",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Message Handling Time (per Message)",
     "type": "graph",
     "description": "Measures how long each kind of request on the C-Chain takes to handle.\\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_C_handler_pull_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m]) / rate(avalanche_C_handler_pull_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_C_handler_push_query_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_push_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_C_handler_chits_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_C_handler_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_C_handler_get_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_get_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_C_handler_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_C_handler_multi_put_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_multi_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_C_handler_get_ancestors_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_get_ancestors_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_C_handler_get_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_get_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_C_handler_query_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_C_handler_get_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_get_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{package=\"avalanche.public.dappnode.eth\"}[1m])/rate(avalanche_C_handler_get_ancestors_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])/1000000000",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Average Block Acceptance Latency",
     "type": "graph",
     "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
     "gridPos": { "h": 9, "w": 6, "x": 13, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_C_accepted_sum{package=\"avalanche.public.dappnode.eth\"}[5m]) / rate(avalanche_C_accepted_count{package=\"avalanche.public.dappnode.eth\"}[5m])",
       "legendFormat": "Avg Acceptance Latency"
      }
     ]
    },
    {
     "title": "Percentage of Successful Queries",
     "type": "graph",
     "description": "Percentage of queries for which we receive chits on time.",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(increase(avalanche_C_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[2m]) + 1) / (increase(avalanche_C_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[2m]) + increase(avalanche_C_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[2m]) + 1)"
      }
     ]
    },
    {
     "title": "Messages Received per Second",
     "type": "graph",
     "description": "Measures how many of each kind of message are received per second on the C-Chain",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(avalanche_C_handler_pull_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "pull query"
      },
      {
       "expr": "rate(avalanche_C_handler_push_query_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "push query"
      },
      {
       "expr": "rate(avalanche_C_handler_chits_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "chits"
      },
      {
       "expr": "rate(avalanche_C_handler_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "accepted"
      },
      {
       "expr": "rate(avalanche_C_handler_get_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get"
      },
      {
       "expr": "rate(avalanche_C_handler_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "put"
      },
      {
       "expr": "rate(avalanche_C_handler_multi_put_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "multiput"
      },
      {
       "expr": "rate(avalanche_C_handler_get_ancestors_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get ancestors"
      },
      {
       "expr": "rate(avalanche_C_handler_get_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get failed"
      },
      {
       "expr": "rate(avalanche_C_handler_query_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "query failed"
      },
      {
       "expr": "rate(avalanche_C_handler_get_accepted_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get accepted"
      },
      {
       "expr": "rate(avalanche_C_handler_get_ancestors_failed_count{package=\"avalanche.public.dappnode.eth\"}[1m])",
       "legendFormat": "get ancestors failed"
      }
     ]
    },
    {
     "title": "Unprocessed Incoming Messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avalanche_C_handler_pending", "legendFormat": "Pending Messages" }
     ]
    }
   ]
  }
 ]
}