version: "3.5"
services:
  avalanche:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.7.14
    image: "avalanche.avalanche.public.dappnode.eth:0.1.0"
    volumes:
      - "chain:/root/.avalanchego/db"
      - "validator:/root/.avalanchego/staking"
    environment:
      - P2P_PORT=21061
      - EXTRA_OPT=""
    ports:
      - "21061:21061/tcp"
    restart: unless-stopped
  wallet:
    build:
      context: build-ui
    image: "wallet.avalanche.public.dappnode.eth:0.1.0"
    restart: unless-stopped
volumes:
  chain: {}
  validator: {}
