version: "3.5"
services:
  avalanche:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.12.1
    image: avalanche.avalanche.public.dappnode.eth:0.1.0
    volumes:
      - chain:/root/.avalanchego/db
      - validator:/root/.avalanchego/staking
    environment:
      - EXTRA_OPTS
    ports:
      - "9651"
    restart: unless-stopped
  wallet:
    build:
      context: build-ui
    image: wallet.avalanche.public.dappnode.eth:0.1.0
    restart: unless-stopped
volumes:
  chain: {}
  validator: {}
